/* ── Trip Planner JS ── */

document.addEventListener('DOMContentLoaded', function () {
  // Init selectors
  initBudgetSelector('budgetSelector', 'budgetTier');
  initInterestTags('interestTags', 'selectedInterests');

  // Set default start date to today
  const startDate = document.getElementById('startDate');
  if (startDate) {
    const today = new Date().toISOString().split('T')[0];
    startDate.value = today;
  }

  // Form submit
  const form = document.getElementById('tripForm');
  if (form) {
    form.addEventListener('submit', function (e) {
      e.preventDefault();
      generateItinerary();
    });
  }
});

function generateItinerary() {
  const destination = document.getElementById('destination').value.trim();
  const days = parseInt(document.getElementById('days').value) || 5;
  const budgetTier = document.getElementById('budgetTier').value;
  const groupType = document.getElementById('groupType').value;
  const interests = document.getElementById('selectedInterests').value || 'Culture, Food';
  const special = document.getElementById('specialRequests').value.trim();

  if (!destination) {
    showToast('Please enter a destination.', 'error');
    document.getElementById('destination').focus();
    return;
  }

  // Show loading
  document.getElementById('resultPlaceholder').classList.add('d-none');
  document.getElementById('resultContent').classList.add('d-none');
  document.getElementById('resultLoading').classList.remove('d-none');

  // Animate loading steps
  animateLoadingSteps();

  const btn = document.getElementById('generateBtn');
  btn.disabled = true;
  btn.innerHTML = '<span class="spinner-border spinner-border-sm me-2"></span>Generating...';

  const interestsWithSpecial = interests + (special ? ', ' + special : '');

  fetch('/api/generate-itinerary', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      destination,
      days,
      budget: budgetTier,
      group_type: groupType,
      interests: interestsWithSpecial
    })
  })
    .then(r => r.json())
    .then(data => {
      document.getElementById('resultLoading').classList.add('d-none');
      if (data.error) {
        showToast('Error: ' + data.error, 'error');
        document.getElementById('resultPlaceholder').classList.remove('d-none');
      } else {
        showItinerary(data, destination, days, budgetTier);
      }
    })
    .catch(err => {
      document.getElementById('resultLoading').classList.add('d-none');
      document.getElementById('resultPlaceholder').classList.remove('d-none');
      showToast('Request failed: ' + err.message, 'error');
    })
    .finally(() => {
      btn.disabled = false;
      btn.innerHTML = '<i class="bi bi-stars me-2"></i>Generate AI Itinerary';
    });
}

function showItinerary(data, destination, days, budget) {
  const content = document.getElementById('resultContent');
  const output = document.getElementById('itineraryOutput');
  const title = document.getElementById('resultTitle');
  const meta = document.getElementById('resultMeta');

  title.textContent = `${days}-Day ${destination} Itinerary`;
  meta.textContent = `${budget} · ${document.getElementById('groupType').value} · Generated by IBM Granite AI`;
  output.innerHTML = formatMarkdown(data.itinerary);
  content.classList.remove('d-none');

  // Scroll to result on mobile
  if (window.innerWidth < 992) {
    content.scrollIntoView({ behavior: 'smooth', block: 'start' });
  }

  // Store for copy
  window._lastItinerary = data.itinerary;
}

function animateLoadingSteps() {
  const steps = ['step1', 'step2', 'step3', 'step4'];
  const labels = ['Analyzing destination', 'Building day-wise schedule', 'Finding accommodations', 'Calculating budget'];
  let i = 0;

  // Reset
  steps.forEach((id, idx) => {
    const el = document.getElementById(id);
    if (el) {
      el.className = 'loading-step';
      el.innerHTML = `<i class="bi bi-circle"></i> ${labels[idx]}`;
    }
  });

  function activateNext() {
    if (i < steps.length) {
      const el = document.getElementById(steps[i]);
      if (el) {
        el.className = 'loading-step active';
        el.innerHTML = `<i class="bi bi-check-circle-fill"></i> ${labels[i]}`;
      }
      i++;
      setTimeout(activateNext, 1200);
    }
  }
  activateNext();
}

window.copyItinerary = function () {
  if (window._lastItinerary) {
    copyToClipboard(window._lastItinerary);
  }
};

window.newItinerary = function () {
  document.getElementById('resultContent').classList.add('d-none');
  document.getElementById('resultPlaceholder').classList.remove('d-none');
  document.getElementById('destination').focus();
};
